# Default k9s plugin location is ~/k9s/plugin.yml
# vsc is a script to randomize a file name and launch Visual Studio Code on WSL2.
# "code -" might be usable without a script on Mac, but it's broken on Windows and needs this script.

plugin:
  debug:
    shortCut: Shift-D
    confirm: false
    description: Debug Container
    scopes:
    - containers
    command: bash
    background: false
    args:
    - -c
    - |
      kubectl debug -it --context $CONTEXT -n $NAMESPACE $POD --target $NAME --image nicolaka/netshoot
  envoyStatsToVSC:
    shortCut: Shift-1
    confirm: false
    description: Envoy stats > VSC
    scopes:
    - pods
    command: bash
    background: false
    args:
    - -c
    - |
      kubectl exec --context ${CONTEXT} -n ${NAMESPACE} ${NAME} -- /usr/bin/curl -s localhost:19000/stats | sort | vsc
  envoyClustersToVSC:
    shortCut: Shift-2
    confirm: false
    description: Envoy clusters > VSC
    scopes:
    - pods
    command: bash
    background: false
    args:
    - -c
    - |
      kubectl exec --context ${CONTEXT} -n ${NAMESPACE} ${NAME} -- /usr/bin/curl -s localhost:19000/clusters | sort | vsc
  envoyConfigDumpToVSC:
    shortCut: Shift-3
    confirm: false
    description: Envoy config_dump > VSC
    scopes:
    - pods
    command: bash
    background: false
    args:
    - -c
    - |
      kubectl exec --context ${CONTEXT} -n ${NAMESPACE} ${NAME} -- /usr/bin/curl -s localhost:19000/config_dump | vsc json